### ISSUE TITLE
Zmoki

### ISSUE THREAD

**Issue by talgautb** [talgautb/frontenders#39]
@Zmoki привет! Извини за уведомление, но было бы круто увидеть тебя в нашем [списке](https://github.com/talgautb/frontenders/blob/master/ru.md), можно отправить PR или отписать информацию о себе, я добавлю :)
о том как это сделать можно прочитать [здесь](https://github.com/talgautb/frontenders/blob/master/Contributing.md)

**Comment by Zmoki** [comment]
Привет! Внезапно)) Сделаю PR ;)

**Comment by talgautb** [comment]
@Zmoki отлично! ждём ;)

**Comment by talgautb** [comment]
ждём :) @Zmoki

**Comment by talgautb** [comment]
@Zmoki напомню, вдруг забыла ;)
