### ISSUE TITLE
Una Kravets

### ISSUE THREAD

**Issue by talgautb** [talgautb/frontenders#40]
Hi @una !
We have a list of awesome frontenders and we want you to be there.
Can you send PR about youself to our repo? or leave comment here. some example [here](https://github.com/talgautb/frontenders/blob/master/en.md)
p.s. Sorry for mention.

**Comment by una** [comment]
sure :)

## Una Kravets

UI Engineer at [DigitalOcean](http://digitalocean.com). Technical [writer](http://una.im), [speaker](http://una.im/speaking), cohost of the [Toolsday Podcast](http://toolsday.io), and creator of [CSSgram](http://una.im/CSSgram).

[una.im](http://una.im), [@una](http://twitter.com/una), [github](http://github.com/una)
