### ISSUE TITLE
Paul Irish

### ISSUE THREAD

**Issue by talgautb** [talgautb/frontenders#41]
Hi @paulirish !
We have a list of awesome frontenders and we want you to be there.
Can you send PR about youself to our repo? you can find some example [here](https://github.com/talgautb/frontenders/blob/master/en.md)
p.s. Sorry for mention ¯\\_(ツ)_/¯

**Comment by ihorzenich** [comment]
@talgautb just add him as you already added Russian-speaking devs. It is not necessary to ask permission. Just add, please. And create a twitter list based on your list.
