### ISSUE TITLE
Кого добавить?

### ISSUE THREAD

**Issue by talgautb** [talgautb/frontenders#8]
Кандидаты

**Comment by talgautb** [comment]
Можно в комментариях предлагать кандидатуру :)
для этого прочтите [правила](https://github.com/talgautb/frontender/blob/master/Contributing.md)

**Comment by talgautb** [comment]
@legomushroom @Likita не хотите отправить PR или комментарий (я добавлю) о себе?

**Comment by legomushroom** [comment]
@talgautb буду рад. Сделаю на днях.

**Comment by talgautb** [comment]
@legomushroom может комментарий?

**Comment by legomushroom** [comment]
@talgautb упс, прошу прощения. Давайте попробуем комментарием,
### Олег Соломка
Создатель [mojs](http://mojs.io/). Aвтор для [codrops](http://tympanus.net/codrops/) и [smashingmagazine](https://www.smashingmagazine.com/). 

[twitter](https://twitter.com/legomushroom/) [github](https://github.com/legomushroom) [codepen](http://codepen.io/sol0mka/)
